### ISSUE TITLE
Running images as non root

### ISSUE THREAD

**Issue by matt-couchman** [genomehubs/search-docker#1]
Hi Richard,

Many thanks for all your help, we've got a version of GenomeHubs that is looking good for internal use. To publish externally we have to pass our network admin's security audit and that has highlighted that some of the images are being run as root. Specifically the docker bench tool (https://github.com/docker/docker-bench-security) reports that:

```
[INFO] 4 - Container Images and Build File
[WARN] 4.1  - Ensure a user for the container has been created
[WARN]      * Running as root: genomehubs-sequenceserver
[WARN]      * Running as root: genomehubs-download
[WARN]      * Running as root: genomehubs-search
```

I noticed that this is something that you have looked at for some of the other images, for example the easy-import container is invoked with the ``-u $UID:$GROUPS`` flag and makes use of the eguser in the Docker container.

How difficult do you think it would be to make the containers above run as non-root users?

Best wishes,

Matt.

**Comment by rjchallis** [comment]
Thanks for pointing this out.

I've updated the containers and uploaded the new images to docker hub with the`19.05` and `latest` tags.
